part of 'message.dart';

///
/// Wrapping a standart socket
class _AnySocketRaw implements _AnySocket {
  final _log = Log('_AnySocketRaw');
  final Socket _socket;
  ///
  ///
  _AnySocketRaw(Socket socket):
    _socket = socket;
  ///
  ///
  @override
  StreamSubscription<List<int>> listen(
    void Function(List<int>)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) {
    _log.debug('.listen | ...');
    return _socket.listen(onData, onError: onError, onDone: onDone);
  }
  ///
  /// Adds byte [data] to the target consumer, ignoring [encoding].
  /// 
  /// The [encoding] does not apply to this method, and the [data] list is passed directly to the target consumer as a stream event.
  /// 
  /// This method must not be called when a stream is currently being added using [addStream].
  /// 
  /// This operation is non-blocking. See [flush] or [done] for how to get any errors generated by this call.
  /// 
  /// The data list should not be modified after it has been passed to add because it is not defined whether the target consumer will receive the list in the original or modified state.
  /// 
  /// Individual values in [data] which are not in the range 0 .. 255 will be truncated to their low eight bits, as if by [int.toUnsigned], before being used.
  @override
  void add(data) {
    _log.debug('.add | data...');
    _socket.add(data);
    _log.debug('.add | data - Done');
  }
  ///
  /// Returns a [Future] that completes once all buffered data is accepted by the underlying [StreamConsumer].
  /// 
  /// This method must not be called while an [addStream] is incomplete.
  /// 
  /// NOTE: This is not necessarily the same as the data being flushed by the operating system.
  @override
  Future<dynamic> flush() {
    return _socket.flush();
  }
  ///
  /// Close the target consumer.
  /// 
  /// NOTE: Writes to the [IOSink] may be buffered, and may not be flushed by a call to close(). To flush all buffered writes, call flush() before calling close().
  /// 
  /// Copied from IOSink.
  @override
  Future<dynamic> close() {
    return _socket.close();
  }
}
